site_name: "MANGO"
site_url: http://mango.ttic.edu
nav:
    - Home: index.md
    - Data: data.md
    - Leaderboard: leaderboard.md
    - Code: https://github.com/Oaklight/mango
    - Contact: contact.md
theme: 
    name: material
    logo: ./assets/images/mango.png
    favicon: ./assets/images/mango-favicon-16x16.png
    palette:
        primary: amber
        accent: amber
