name: CI for MkDocs Github Pages
on:
  push:
    branches: [website]
  pull_request:
    branches: [website]
permissions:
  contents: write

jobs:
  build:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Website branch
        uses: actions/checkout@v3
        with:
          ref: 'website'
      
      - name: setup python3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      
      - name: install dependencies
        run: pip install mkdocs-material 
      
      - deploy to gh-pages
        run: mkdocs gh-deploy --force
